# Generated by Django 2.2.11 on 2020-05-17 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_product',
            name='categories',
        ),
        migrations.AddField(
            model_name='book_product',
            name='sub_categories',
            field=models.ManyToManyField(related_name='books', to='baseapp.Category'),
        ),
    ]
